# Importing Liberaries

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyp

# Q1

In [2]:
fact_df = pd.read_csv('../data/fact.csv', delimiter='\t')
fact_df.head(5)

,Row ID,Order ID,Product ID,Customer ID,Geo ID,Date ID,Sales,Quantity,Discount,Profit,Shipping Cost
0,422,MX-2014-106901,OFF-FA-10002084,LS-17200,MX-2014-106901,MX-2014-106901,17.480000,2,0.0,0.0,1.684000
1,957,MX-2014-105921,TEC-AC-10004626,ZC-21910,MX-2014-105921,MX-2014-105921,342.079987,2,0.0,0.0,21.712999
2,1292,MX-2013-118402,OFF-BI-10001304,JM-15250,MX-2013-118402,MX-2013-118402,38.880001,2,0.0,0.0,5.923000
3,1607,MX-2013-110933,TEC-PH-10003935,SN-20560,MX-2013-110933,MX-2013-110933,186.360001,2,0.0,0.0,19.783001
4,1941,MX-2011-116246,OFF-SU-10003371,RL-19615,MX-2011-116246,MX-2011-116246,58.279999,2,0.0,0.0,8.203000

In [3]:
product_df = pd.read_csv("../data/cleanized/product_dim.csv")
product_df.head(5)

,Product ID,Product Name,Sub-Category_Accessories,Sub-Category_Appliances,Sub-Category_Art,Sub-Category_Binders,Sub-Category_Bookcases,Sub-Category_Chairs,Sub-Category_Copiers,Sub-Category_Envelopes,...,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables,Category_Furniture,Category_Office Supplies,Category_Technology
0,OFF-EAT-10000522,"Eaton Computer Printout Paper, Multicolor",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
1,OFF-EAT-10000652,"Eaton Computer Printout Paper, 8.5 x 11",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
2,OFF-EAT-10000820,"Eaton Message Books, Multicolor",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
3,OFF-EAT-10000854,"Eaton Parchment Paper, Recycled",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
4,OFF-EAT-10001025,"Eaton Note Cards, Multicolor",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [4]:
order_df = pd.read_csv("../data/cleanized/order_dim.csv")
order_df.head(5)

,Order ID,Order Priority,Returned,Ship Mode_First Class,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Market_APAC,Market_Africa,Market_Canada,Market_EMEA,Market_EU,Market_LATAM,Market_US
0,ID-2011-11126,2,False,False,False,False,True,True,False,False,False,False,False,False
1,ID-2011-11385,2,False,False,False,False,True,True,False,False,False,False,False,False
2,ID-2011-12596,2,False,False,False,False,True,True,False,False,False,False,False,False
3,ID-2011-13114,2,False,False,False,False,True,True,False,False,False,False,False,False
4,ID-2011-13170,2,False,False,False,False,True,True,False,False,False,False,False,False

In [5]:
geo_df = pd.read_csv("../data/cleanized/geo_dim.csv")
geo_df.head(5)

,Geo ID,City,State,Region_Africa,Region_Canada,Region_Caribbean,Region_Central,Region_Central Asia,Region_EMEA,Region_East,...,Country_United Arab Emirates,Country_United Kingdom,Country_United States,Country_Uruguay,Country_Uzbekistan,Country_Venezuela,Country_Vietnam,Country_Yemen,Country_Zambia,Country_Zimbabwe
0,CA-2013-159016,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,CA-2012-149846,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,CA-2011-106726,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,US-2013-116729,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,CA-2014-133865,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [6]:
df = fact_df.set_index("Product ID", drop= False).join(product_df.set_index("Product ID", drop= False), rsuffix= "_product")\
              .set_index("Order ID", drop= False).join(order_df.set_index("Order ID", drop= False), rsuffix= "_order")\
              .set_index("Geo ID", drop= False).join(geo_df.set_index("Geo ID", drop= False), rsuffix = "_geo")
df.head(5)

,Row ID,Order ID,Product ID,Customer ID,Geo ID,Date ID,Sales,Quantity,Discount,Profit,...,Country_United Arab Emirates,Country_United Kingdom,Country_United States,Country_Uruguay,Country_Uzbekistan,Country_Venezuela,Country_Vietnam,Country_Yemen,Country_Zambia,Country_Zimbabwe
Geo ID,,,,,,,,,,,,,,,,,,,,,
AE-2011-9160,48313,AE-2011-9160,OFF-FEL-10001405,PO-8865,AE-2011-9160,AE-2011-9160,82.674004,2,0.7,-157.085999,...,True,False,False,False,False,False,False,False,False,False
AE-2011-9160,48312,AE-2011-9160,TEC-EPS-10004171,PO-8865,AE-2011-9160,AE-2011-9160,78.407997,6,0.7,-88.991997,...,True,False,False,False,False,False,False,False,False,False
AE-2013-1130,47298,AE-2013-1130,FUR-BUS-10003055,EB-4110,AE-2013-1130,AE-2013-1130,224.748001,6,0.7,-232.272003,...,True,False,False,False,False,False,False,False,False,False
AE-2013-1130,47297,AE-2013-1130,OFF-ACC-10004278,EB-4110,AE-2013-1130,AE-2013-1130,4.248000,1,0.7,-4.692000,...,True,False,False,False,False,False,False,False,False,False
AE-2013-1530,48618,AE-2013-1530,OFF-STI-10000114,MY-7380,AE-2013-1530,AE-2013-1530,16.667999,2,0.7,-29.472000,...,True,False,False,False,False,False,False,False,False,False

In [7]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Product ID',
 'Customer ID',
 'Geo ID',
 'Date ID',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Cost',
 'Product ID_product',
 'Product Name',
 'Sub-Category_Accessories',
 'Sub-Category_Appliances',
 'Sub-Category_Art',
 'Sub-Category_Binders',
 'Sub-Category_Bookcases',
 'Sub-Category_Chairs',
 'Sub-Category_Copiers',
 'Sub-Category_Envelopes',
 'Sub-Category_Fasteners',
 'Sub-Category_Furnishings',
 'Sub-Category_Labels',
 'Sub-Category_Machines',
 'Sub-Category_Paper',
 'Sub-Category_Phones',
 'Sub-Category_Storage',
 'Sub-Category_Supplies',
 'Sub-Category_Tables',
 'Category_Furniture',
 'Category_Office Supplies',
 'Category_Technology',
 'Order ID_order',
 'Order Priority',
 'Returned',
 'Ship Mode_First Class',
 'Ship Mode_Same Day',
 'Ship Mode_Second Class',
 'Ship Mode_Standard Class',
 'Market_APAC',
 'Market_Africa',
 'Market_Canada',
 'Market_EMEA',
 'Market_EU',
 'Market_LATAM',
 'Market_US',
 'Geo ID_geo',
 'City',
 'State',
 'Region_Africa',
 'Region_Canada',
 'Region_Caribbean',
 'Region_Central',
 'Region_Central Asia',
 'Region_EMEA',
 'Region_East',
 'Region_North',
 'Region_North Asia',
 'Region_Oceania',
 'Region_South',
 'Region_Southeast Asia',
 'Region_West',
 'Country_Afghanistan',
 'Country_Albania',
 'Country_Algeria',
 'Country_Angola',
 'Country_Argentina',
 'Country_Armenia',
 'Country_Australia',
 'Country_Austria',
 'Country_Azerbaijan',
 'Country_Bahrain',
 'Country_Bangladesh',
 'Country_Barbados',
 'Country_Belarus',
 'Country_Belgium',
 'Country_Benin',
 'Country_Bolivia',
 'Country_Bosnia and Herzegovina',
 'Country_Brazil',
 'Country_Bulgaria',
 'Country_Burundi',
 'Country_Cambodia',
 'Country_Cameroon',
 'Country_Canada',
 'Country_Central African Republic',
 'Country_Chad',
 'Country_Chile',
 'Country_China',
 'Country_Colombia',
 "Country_Cote d'Ivoire",
 'Country_Croatia',
 'Country_Cuba',
 'Country_Czech Republic',
 'Country_Democratic Republic of the Congo',
 'Country_Denmark',
 'Country_Djibouti',
 'Country_Dominican Republic',
 'Country_Ecuador',
 'Country_Egypt',
 'Country_El Salvador',
 'Country_Equatorial Guinea',
 'Country_Eritrea',
 'Country_Estonia',
 'Country_Ethiopia',
 'Country_Finland',
 'Country_France',
 'Country_Gabon',
 'Country_Georgia',
 'Country_Germany',
 'Country_Ghana',
 'Country_Guadeloupe',
 'Country_Guatemala',
 'Country_Guinea',
 'Country_Guinea-Bissau',
 'Country_Haiti',
 'Country_Honduras',
 'Country_Hong Kong',
 'Country_Hungary',
 'Country_India',
 'Country_Indonesia',
 'Country_Iran',
 'Country_Iraq',
 'Country_Ireland',
 'Country_Israel',
 'Country_Italy',
 'Country_Jamaica',
 'Country_Japan',
 'Country_Jordan',
 'Country_Kazakhstan',
 'Country_Kenya',
 'Country_Kyrgyzstan',
 'Country_Lebanon',
 'Country_Lesotho',
 'Country_Liberia',
 'Country_Libya',
 'Country_Lithuania',
 'Country_Macedonia',
 'Country_Madagascar',
 'Country_Malaysia',
 'Country_Mali',
 'Country_Martinique',
 'Country_Mauritania',
 'Country_Mexico',
 'Country_Moldova',
 'Country_Mongolia',
 'Country_Montenegro',
 'Country_Morocco',
 'Country_Mozambique',
 'Country_Myanmar (Burma)',
 'Country_Namibia',
 'Country_Nepal',
 'Country_Netherlands',
 'Country_New Zealand',
 'Country_Nicaragua',
 'Country_Niger',
 'Country_Nigeria',
 'Country_Norway',
 'Country_Pakistan',
 'Country_Panama',
 'Country_Papua New Guinea',
 'Country_Paraguay',
 'Country_Peru',
 'Country_Philippines',
 'Country_Poland',
 'Country_Portugal',
 'Country_Qatar',
 'Country_Republic of the Congo',
 'Country_Romania',
 'Country_Russia',
 'Country_Rwanda',
 'Country_Saudi Arabia',
 'Country_Senegal',
 'Country_Sierra Leone',
 'Country_Singapore',
 'Country_Slovakia',
 'Country_Slovenia',
 'Country_Somalia',
 'Country_South Africa',
 'Country_South Korea',
 'Country_South Sudan',
 'Country_Spain',
 'Country_Sri Lanka',
 'Country_Sudan',
 'Country_Swaziland',
 'Country_Sweden',
 'Country_Switzerland',
 'Country_Syria',
 'Country_Taiwan',
 'Country_Tajikistan',
 'Country_Tanzania',
 'Country_Thailand',
 'Country_Togo',
 'Country_Trinidad and Tobago',
 'Country_Tunisia',
 'Country_Turkey',
 'Country_Turkmenistan',
 'Country_Uganda',
 'Country_Ukraine',
 'Country_United Arab Emirates',
 'Country_United Kingdom',
 'Country_United States',
 'Country_Uruguay',
 'Country_Uzbekistan',
 'Country_Venezuela',
 'Country_Vietnam',
 'Country_Yemen',
 'Country_Zambia',
 'Country_Zimbabwe']

In [8]:
X = df.drop(['Profit', 'Row ID', 'Order ID', 'Product ID', 'Customer ID', 'Geo ID', 'Date ID',\
    'Product ID_product', 'Product Name', 'Order ID_order', 'Geo ID_geo', 'City', 'State'], axis=1)
X

,Sales,Quantity,Discount,Shipping Cost,Sub-Category_Accessories,Sub-Category_Appliances,Sub-Category_Art,Sub-Category_Binders,Sub-Category_Bookcases,Sub-Category_Chairs,...,Country_United Arab Emirates,Country_United Kingdom,Country_United States,Country_Uruguay,Country_Uzbekistan,Country_Venezuela,Country_Vietnam,Country_Yemen,Country_Zambia,Country_Zimbabwe
Geo ID,,,,,,,,,,,,,,,,,,,,,
AE-2011-9160,82.674004,2,0.7,5.690000,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
AE-2011-9160,78.407997,6,0.7,3.870000,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
AE-2013-1130,224.748001,6,0.7,60.080002,False,False,False,False,True,False,...,True,False,False,False,False,False,False,False,False,False
AE-2013-1130,4.248000,1,0.7,0.100000,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
AE-2013-1530,16.667999,2,0.7,1.410000,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZI-2014-7610,21.500999,1,0.7,2.250000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
ZI-2014-9540,7.164000,2,0.7,0.350000,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
ZI-2014-9550,1.161000,1,0.7,0.070000,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,True
ZI-2014-9550,71.639999,2,0.7,4.050000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
ZI-2014-9650,4.104000,1,0.7,0.800000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [9]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49670 entries, AE-2011-9160 to ZI-2014-9650
Columns: 197 entries, Sales to Country_Zimbabwe
dtypes: bool(192), float64(3), int64(2)
memory usage: 11.4+ MB

In [10]:
y = np.array(df["Profit"])
y

array([-157.08599854,  -88.99199677, -232.27200317, ...,   -2.34899998,
        -93.18000031,   -4.80600023])

In [11]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from flaml import AutoML
from sklearn.decomposition import PCA

In [12]:
# Standardization and Normalization
min_max_scaler = MinMaxScaler()

min_max_scaler.fit(X)
min_max_scaled = min_max_scaler.transform(X)
min_max_scaled_df = pd.DataFrame(min_max_scaled, columns=X.columns)

std_scaler = StandardScaler()

std_scaler.fit(min_max_scaled_df)
scaled = std_scaler.transform(min_max_scaled_df)
scaled_df = pd.DataFrame(scaled, columns= min_max_scaled_df.columns)

In [21]:
# PCA transformation
pca_transformer = PCA(n_components=0.99, svd_solver = 'auto')
pca_transformer.fit(scaled_df)
reduced_X = pca_transformer.transform(scaled_df)
reduced_X

array([[-3.44961978, -2.55548413, -4.12160336, ...,  4.69673044,
        -0.06097149,  0.13585723],
       [-1.55206055, -2.62121906, -4.17912987, ...,  4.23718016,
        -0.12980008, -0.44657495],
       [-0.91986515, -2.21020041, -4.23951071, ...,  2.01406092,
        -0.2098323 , -1.24791856],
       ...,
       [-3.47100429, -2.34662757,  3.98088781, ...,  0.0493894 ,
        -0.27066785,  0.49688988],
       [-1.66821428, -2.67387977,  3.9644197 , ..., -0.39903823,
        -0.41427182,  0.06218339],
       [-3.21814955, -2.52060404,  4.1179807 , ..., -0.43732361,
        -0.27317365,  0.80440231]])

In [22]:
reduced_X.shape

(49670, 169)

In [23]:
# Without PCA
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=313)

In [24]:
lrmodel = LinearRegression()
lrmodel.fit(x_train, y_train)
y_pred = lrmodel.predict(x_test)
r2_score(y_test, y_pred)

0.25681498948265635

In [25]:
amlmodel = AutoML(task= "regression", time_budget= 60, verbose=0)
amlmodel.fit(x_train, y_train)
y_pred = amlmodel.predict(x_test)
r2_score(y_test, y_pred)

0.7114524962050922

In [26]:
# With PCA
x_train, x_test, y_train, y_test = train_test_split(reduced_X,y, test_size=.2, random_state=313)

In [27]:
lrmodel = LinearRegression()
lrmodel.fit(x_train, y_train)
y_pred = lrmodel.predict(x_test)
r2_score(y_test, y_pred)

0.20103486705701012

In [28]:
amlmodel = AutoML(task= "regression", time_budget= 60, verbose=0)
amlmodel.fit(x_train, y_train)
y_pred = amlmodel.predict(x_test)
r2_score(y_test, y_pred)

0.5098503407048816