# Importing Liberaries

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyp

# Q1

In [7]:
df = pd.read_csv('../data/fact.csv', delimiter='\t')
df.head(5)

,Row ID,Order ID,Product ID,Customer ID,Geo ID,Date ID,Sales,Quantity,Discount,Profit,Shipping Cost
0,422,MX-2014-106901,OFF-FA-10002084,LS-17200,MX-2014-106901,MX-2014-106901,17.480000,2,0.0,0.0,1.684000
1,957,MX-2014-105921,TEC-AC-10004626,ZC-21910,MX-2014-105921,MX-2014-105921,342.079987,2,0.0,0.0,21.712999
2,1292,MX-2013-118402,OFF-BI-10001304,JM-15250,MX-2013-118402,MX-2013-118402,38.880001,2,0.0,0.0,5.923000
3,1607,MX-2013-110933,TEC-PH-10003935,SN-20560,MX-2013-110933,MX-2013-110933,186.360001,2,0.0,0.0,19.783001
4,1941,MX-2011-116246,OFF-SU-10003371,RL-19615,MX-2011-116246,MX-2011-116246,58.279999,2,0.0,0.0,8.203000

In [13]:
X = df.drop(['Profit', 'Row ID', 'Order ID', 'Product ID', 'Customer ID', 'Geo ID', 'Date ID'], axis=1)
X

            Sales  Quantity  Discount  Shipping Cost
0       17.480000         2       0.0       1.684000
1      342.079987         2       0.0      21.712999
2       38.880001         2       0.0       5.923000
3      186.360001         2       0.0      19.783001
4       58.279999         2       0.0       8.203000
...           ...       ...       ...            ...
49665   21.360001         2       0.6       3.140000
49666   97.655998         2       0.6      15.340000
49667   37.632000         2       0.6       0.090000
49668   93.047997         2       0.6      19.290001
49669  153.192001         2       0.6       7.960000

[49670 rows x 4 columns]

In [17]:
from sklearn.preprocessing import MinMaxScaler

X = df.drop(['Profit', 'Row ID', 'Order ID', 'Product ID', 'Customer ID', 'Geo ID', 'Date ID'], axis=1)
scaler = MinMaxScaler()
scaler.fit(X)
scaled = scaler.fit_transform(X)
scaled_df = pd.DataFrame(scaled, columns=X.columns)
scaled_df

          Sales  Quantity  Discount  Shipping Cost
0      0.000753  0.076923  0.000000       0.001802
1      0.015091  0.076923  0.000000       0.023256
2      0.001698  0.076923  0.000000       0.006342
3      0.008213  0.076923  0.000000       0.021189
4      0.002555  0.076923  0.000000       0.008785
...         ...       ...       ...            ...
49665  0.000924  0.076923  0.705882       0.003361
49666  0.004294  0.076923  0.705882       0.016429
49667  0.001643  0.076923  0.705882       0.000094
49668  0.004091  0.076923  0.705882       0.020661
49669  0.006747  0.076923  0.705882       0.008524

[49670 rows x 4 columns]

In [22]:
from sklearn.decomposition import PCA

pca_transformer = PCA(n_components=2,)

pca_transformer.fit(scaled_df)

PCA(n_components=2)

In [23]:
reduced_X = pca_transformer.transform(scaled_df)
reduced_X

array([[-0.16464944, -0.12029624],
       [-0.16523445, -0.11742629],
       [-0.16475595, -0.11977504],
       ...,
       [ 0.5408371 , -0.10048826],
       [ 0.5403699 , -0.09820321],
       [ 0.54061162, -0.09938242]])

In [ ]:
# modeling
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

X = df.drop(['name', 'target_5yrs'], axis=1)
y = df.target_5yrs

x_train,x_test , y_train,y_test = train_test_split(X,y, test_size=.2, random_state=313)

std_scaler = StandardScaler()
x_train = std_scaler.fit_transform(x_train)