# Importing Liberaries

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyp

# Q1

In [2]:
fact_df = pd.read_csv('../data/fact.csv', delimiter='\t')
fact_df.head(5)

,Row ID,Order ID,Product ID,Customer ID,Geo ID,Date ID,Sales,Quantity,Discount,Profit,Shipping Cost
0,422,MX-2014-106901,OFF-FA-10002084,LS-17200,MX-2014-106901,MX-2014-106901,17.480000,2,0.0,0.0,1.684000
1,957,MX-2014-105921,TEC-AC-10004626,ZC-21910,MX-2014-105921,MX-2014-105921,342.079987,2,0.0,0.0,21.712999
2,1292,MX-2013-118402,OFF-BI-10001304,JM-15250,MX-2013-118402,MX-2013-118402,38.880001,2,0.0,0.0,5.923000
3,1607,MX-2013-110933,TEC-PH-10003935,SN-20560,MX-2013-110933,MX-2013-110933,186.360001,2,0.0,0.0,19.783001
4,1941,MX-2011-116246,OFF-SU-10003371,RL-19615,MX-2011-116246,MX-2011-116246,58.279999,2,0.0,0.0,8.203000

In [3]:
product_df = pd.read_csv("../data/cleanized/product_dim.csv")
product_df.head(5)

,Product ID,Product Name,Sub-Category_Accessories,Sub-Category_Appliances,Sub-Category_Art,Sub-Category_Binders,Sub-Category_Bookcases,Sub-Category_Chairs,Sub-Category_Copiers,Sub-Category_Envelopes,...,Sub-Category_Labels,Sub-Category_Machines,Sub-Category_Paper,Sub-Category_Phones,Sub-Category_Storage,Sub-Category_Supplies,Sub-Category_Tables,Category_Furniture,Category_Office Supplies,Category_Technology
0,OFF-EAT-10000522,"Eaton Computer Printout Paper, Multicolor",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
1,OFF-EAT-10000652,"Eaton Computer Printout Paper, 8.5 x 11",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
2,OFF-EAT-10000820,"Eaton Message Books, Multicolor",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
3,OFF-EAT-10000854,"Eaton Parchment Paper, Recycled",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
4,OFF-EAT-10001025,"Eaton Note Cards, Multicolor",False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [4]:
order_df = pd.read_csv("../data/cleanized/order_dim.csv")
order_df.head(5)

,Order ID,Order Priority,Returned,Ship Mode_First Class,Ship Mode_Same Day,Ship Mode_Second Class,Ship Mode_Standard Class,Market_APAC,Market_Africa,Market_Canada,Market_EMEA,Market_EU,Market_LATAM,Market_US
0,ID-2011-11126,2,False,False,False,False,True,True,False,False,False,False,False,False
1,ID-2011-11385,2,False,False,False,False,True,True,False,False,False,False,False,False
2,ID-2011-12596,2,False,False,False,False,True,True,False,False,False,False,False,False
3,ID-2011-13114,2,False,False,False,False,True,True,False,False,False,False,False,False
4,ID-2011-13170,2,False,False,False,False,True,True,False,False,False,False,False,False

In [5]:
geo_df = pd.read_csv("../data/cleanized/geo_dim.csv")
geo_df.head(5)

,Geo ID,City,State,Region_Africa,Region_Canada,Region_Caribbean,Region_Central,Region_Central Asia,Region_EMEA,Region_East,...,Country_United Arab Emirates,Country_United Kingdom,Country_United States,Country_Uruguay,Country_Uzbekistan,Country_Venezuela,Country_Vietnam,Country_Yemen,Country_Zambia,Country_Zimbabwe
0,CA-2013-159016,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,CA-2012-149846,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,CA-2011-106726,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,US-2013-116729,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,CA-2014-133865,Los Angeles,California,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False

In [6]:
customer_df = pd.read_csv("../data/cleanized/customer_dim.csv")
customer_df.head(5)

,Customer ID,Customer Name,Segment_Consumer,Segment_Corporate,Segment_Home Office
0,AA-10315,Alex Avila,True,False,False
1,AA-10375,Allen Armold,True,False,False
2,AA-10480,Andrew Allen,True,False,False
3,AA-10645,Anna Andreadi,True,False,False
4,AA-315,Alex Avila,True,False,False

In [7]:
df = fact_df.set_index("Product ID", drop= False).join(product_df.set_index("Product ID", drop= False), rsuffix= "_product")\
              .set_index("Order ID", drop= False).join(order_df.set_index("Order ID", drop= False), rsuffix= "_order")\
              .set_index("Geo ID", drop= False).join(geo_df.set_index("Geo ID", drop= False), rsuffix = "_geo")\
              .set_index("Customer ID", drop= False).join(customer_df.set_index("Customer ID", drop= False), rsuffix= "_customer")
df.head(5)

,Row ID,Order ID,Product ID,Customer ID,Geo ID,Date ID,Sales,Quantity,Discount,Profit,...,Country_Venezuela,Country_Vietnam,Country_Yemen,Country_Zambia,Country_Zimbabwe,Customer ID_customer,Customer Name,Segment_Consumer,Segment_Corporate,Segment_Home Office
Customer ID,,,,,,,,,,,,,,,,,,,,,
AA-10315,33527,CA-2011-128055,OFF-AP-10002765,AA-10315,CA-2011-128055,CA-2011-128055,52.980000,2,0.0,14.834400,...,False,False,False,False,False,AA-10315,Alex Avila,True,False,False
AA-10315,33526,CA-2011-128055,OFF-BI-10004390,AA-10315,CA-2011-128055,CA-2011-128055,673.567993,2,0.2,252.587997,...,False,False,False,False,False,AA-10315,Alex Avila,True,False,False
AA-10315,38766,CA-2011-138100,FUR-FU-10002456,AA-10315,CA-2011-138100,CA-2011-138100,14.560000,2,0.0,6.260800,...,False,False,False,False,False,AA-10315,Alex Avila,True,False,False
AA-10315,38765,CA-2011-138100,OFF-PA-10000349,AA-10315,CA-2011-138100,CA-2011-138100,14.940000,3,0.0,7.021800,...,False,False,False,False,False,AA-10315,Alex Avila,True,False,False
AA-10315,32596,CA-2012-121391,OFF-ST-10001590,AA-10315,CA-2012-121391,CA-2012-121391,26.959999,2,0.0,7.009600,...,False,False,False,False,False,AA-10315,Alex Avila,True,False,False

In [8]:
df.columns.tolist()

['Row ID',
 'Order ID',
 'Product ID',
 'Customer ID',
 'Geo ID',
 'Date ID',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Cost',
 'Product ID_product',
 'Product Name',
 'Sub-Category_Accessories',
 'Sub-Category_Appliances',
 'Sub-Category_Art',
 'Sub-Category_Binders',
 'Sub-Category_Bookcases',
 'Sub-Category_Chairs',
 'Sub-Category_Copiers',
 'Sub-Category_Envelopes',
 'Sub-Category_Fasteners',
 'Sub-Category_Furnishings',
 'Sub-Category_Labels',
 'Sub-Category_Machines',
 'Sub-Category_Paper',
 'Sub-Category_Phones',
 'Sub-Category_Storage',
 'Sub-Category_Supplies',
 'Sub-Category_Tables',
 'Category_Furniture',
 'Category_Office Supplies',
 'Category_Technology',
 'Order ID_order',
 'Order Priority',
 'Returned',
 'Ship Mode_First Class',
 'Ship Mode_Same Day',
 'Ship Mode_Second Class',
 'Ship Mode_Standard Class',
 'Market_APAC',
 'Market_Africa',
 'Market_Canada',
 'Market_EMEA',
 'Market_EU',
 'Market_LATAM',
 'Market_US',
 'Geo ID_geo',
 'City',
 'State',
 'Region_Africa',
 'Region_Canada',
 'Region_Caribbean',
 'Region_Central',
 'Region_Central Asia',
 'Region_EMEA',
 'Region_East',
 'Region_North',
 'Region_North Asia',
 'Region_Oceania',
 'Region_South',
 'Region_Southeast Asia',
 'Region_West',
 'Country_Afghanistan',
 'Country_Albania',
 'Country_Algeria',
 'Country_Angola',
 'Country_Argentina',
 'Country_Armenia',
 'Country_Australia',
 'Country_Austria',
 'Country_Azerbaijan',
 'Country_Bahrain',
 'Country_Bangladesh',
 'Country_Barbados',
 'Country_Belarus',
 'Country_Belgium',
 'Country_Benin',
 'Country_Bolivia',
 'Country_Bosnia and Herzegovina',
 'Country_Brazil',
 'Country_Bulgaria',
 'Country_Burundi',
 'Country_Cambodia',
 'Country_Cameroon',
 'Country_Canada',
 'Country_Central African Republic',
 'Country_Chad',
 'Country_Chile',
 'Country_China',
 'Country_Colombia',
 "Country_Cote d'Ivoire",
 'Country_Croatia',
 'Country_Cuba',
 'Country_Czech Republic',
 'Country_Democratic Republic of the Congo',
 'Country_Denmark',
 'Country_Djibouti',
 'Country_Dominican Republic',
 'Country_Ecuador',
 'Country_Egypt',
 'Country_El Salvador',
 'Country_Equatorial Guinea',
 'Country_Eritrea',
 'Country_Estonia',
 'Country_Ethiopia',
 'Country_Finland',
 'Country_France',
 'Country_Gabon',
 'Country_Georgia',
 'Country_Germany',
 'Country_Ghana',
 'Country_Guadeloupe',
 'Country_Guatemala',
 'Country_Guinea',
 'Country_Guinea-Bissau',
 'Country_Haiti',
 'Country_Honduras',
 'Country_Hong Kong',
 'Country_Hungary',
 'Country_India',
 'Country_Indonesia',
 'Country_Iran',
 'Country_Iraq',
 'Country_Ireland',
 'Country_Israel',
 'Country_Italy',
 'Country_Jamaica',
 'Country_Japan',
 'Country_Jordan',
 'Country_Kazakhstan',
 'Country_Kenya',
 'Country_Kyrgyzstan',
 'Country_Lebanon',
 'Country_Lesotho',
 'Country_Liberia',
 'Country_Libya',
 'Country_Lithuania',
 'Country_Macedonia',
 'Country_Madagascar',
 'Country_Malaysia',
 'Country_Mali',
 'Country_Martinique',
 'Country_Mauritania',
 'Country_Mexico',
 'Country_Moldova',
 'Country_Mongolia',
 'Country_Montenegro',
 'Country_Morocco',
 'Country_Mozambique',
 'Country_Myanmar (Burma)',
 'Country_Namibia',
 'Country_Nepal',
 'Country_Netherlands',
 'Country_New Zealand',
 'Country_Nicaragua',
 'Country_Niger',
 'Country_Nigeria',
 'Country_Norway',
 'Country_Pakistan',
 'Country_Panama',
 'Country_Papua New Guinea',
 'Country_Paraguay',
 'Country_Peru',
 'Country_Philippines',
 'Country_Poland',
 'Country_Portugal',
 'Country_Qatar',
 'Country_Republic of the Congo',
 'Country_Romania',
 'Country_Russia',
 'Country_Rwanda',
 'Country_Saudi Arabia',
 'Country_Senegal',
 'Country_Sierra Leone',
 'Country_Singapore',
 'Country_Slovakia',
 'Country_Slovenia',
 'Country_Somalia',
 'Country_South Africa',
 'Country_South Korea',
 'Country_South Sudan',
 'Country_Spain',
 'Country_Sri Lanka',
 'Country_Sudan',
 'Country_Swaziland',
 'Country_Sweden',
 'Country_Switzerland',
 'Country_Syria',
 'Country_Taiwan',
 'Country_Tajikistan',
 'Country_Tanzania',
 'Country_Thailand',
 'Country_Togo',
 'Country_Trinidad and Tobago',
 'Country_Tunisia',
 'Country_Turkey',
 'Country_Turkmenistan',
 'Country_Uganda',
 'Country_Ukraine',
 'Country_United Arab Emirates',
 'Country_United Kingdom',
 'Country_United States',
 'Country_Uruguay',
 'Country_Uzbekistan',
 'Country_Venezuela',
 'Country_Vietnam',
 'Country_Yemen',
 'Country_Zambia',
 'Country_Zimbabwe',
 'Customer ID_customer',
 'Customer Name',
 'Segment_Consumer',
 'Segment_Corporate',
 'Segment_Home Office']

In [9]:
X = df.drop(['Profit', 'Row ID', 'Order ID', 'Product ID', 'Customer ID', 'Geo ID', 'Date ID',\
    'Product ID_product', 'Product Name', 'Order ID_order', 'Geo ID_geo', 'City', 'State',\
    'Customer ID_customer', 'Customer Name',], axis=1)
X

,Sales,Quantity,Discount,Shipping Cost,Sub-Category_Accessories,Sub-Category_Appliances,Sub-Category_Art,Sub-Category_Binders,Sub-Category_Bookcases,Sub-Category_Chairs,...,Country_Uruguay,Country_Uzbekistan,Country_Venezuela,Country_Vietnam,Country_Yemen,Country_Zambia,Country_Zimbabwe,Segment_Consumer,Segment_Corporate,Segment_Home Office
Customer ID,,,,,,,,,,,,,,,,,,,,,
AA-10315,52.980000,2,0.000,3.170000,False,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
AA-10315,673.567993,2,0.200,54.959999,False,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False
AA-10315,14.560000,2,0.000,1.310000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
AA-10315,14.940000,3,0.000,0.990000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
AA-10315,26.959999,2,0.000,5.230000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZD-21925,1127.810059,3,0.200,72.709999,False,False,False,False,False,True,...,False,False,False,False,False,False,False,True,False,False
ZD-21925,87.984001,2,0.400,9.110000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
ZD-21925,872.320007,2,0.000,68.222000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
ZD-21925,590.117004,3,0.002,106.680000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
ZD-21925,16.719999,5,0.200,1.930000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49670 entries, AA-10315 to ZD-21925
Columns: 200 entries, Sales to Segment_Home Office
dtypes: bool(195), float64(3), int64(2)
memory usage: 11.5+ MB

In [11]:
y = np.array(df["Profit"])
y

array([ 14.83440018, 252.58799744,   6.26079988, ...,   8.72000027,
        69.73739624,   3.3440001 ])

In [12]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from flaml import AutoML
from sklearn.decomposition import PCA

In [13]:
# Standardization and Normalization
min_max_scaler = MinMaxScaler()

min_max_scaler.fit(X)
min_max_scaled = min_max_scaler.transform(X)
min_max_scaled_df = pd.DataFrame(min_max_scaled, columns=X.columns)

std_scaler = StandardScaler()

std_scaler.fit(min_max_scaled_df)
scaled = std_scaler.transform(min_max_scaled_df)
scaled_df = pd.DataFrame(scaled, columns= min_max_scaled_df.columns)

In [14]:
# PCA transformation
pca_transformer = PCA(n_components=0.99, svd_solver = 'auto')
pca_transformer.fit(scaled_df)
reduced_X = pca_transformer.transform(scaled_df)
reduced_X

array([[-0.93581384,  2.50148602, -0.43132111, ...,  0.96202498,
        -1.3998493 , -0.47462767],
       [-0.72712174,  2.46665659, -0.48408495, ...,  0.08748158,
        -1.06922408,  0.5717498 ],
       [ 0.44318571,  2.71700203, -0.62217267, ...,  0.20095867,
         0.59572283,  0.27719609],
       ...,
       [ 1.51372038,  0.98719168,  0.27794784, ...,  0.88676042,
         0.17957062,  0.47959193],
       [ 1.82225085,  0.53328715,  0.54296974, ...,  0.10696143,
        -1.47411535,  1.24021584],
       [ 0.67797084,  2.49386906, -0.46767269, ...,  0.1746627 ,
        -0.36161546,  1.09822278]])

In [15]:
reduced_X.shape

(49670, 171)

In [16]:
# Without PCA
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=.2, random_state=313)

In [17]:
lrmodel = LinearRegression()
lrmodel.fit(x_train, y_train)
y_pred = lrmodel.predict(x_test)
r2_score(y_test, y_pred)

0.30157638829743627

In [18]:
amlmodel = AutoML(task= "regression", time_budget= 60, verbose=0)
amlmodel.fit(x_train, y_train)
y_pred = amlmodel.predict(x_test)
r2_score(y_test, y_pred)

0.7247340589608697

In [19]:
# With PCA
x_train, x_test, y_train, y_test = train_test_split(reduced_X,y, test_size=.2, random_state=313)

In [20]:
lrmodel = LinearRegression()
lrmodel.fit(x_train, y_train)
y_pred = lrmodel.predict(x_test)
r2_score(y_test, y_pred)

0.2544612783000012

In [21]:
amlmodel = AutoML(task= "regression", time_budget= 60, verbose=0)
amlmodel.fit(x_train, y_train)
y_pred = amlmodel.predict(x_test)
r2_score(y_test, y_pred)

0.42841690258263787